spring:
  datasource:
    url: jdbc:mysql://localhost:3306/exam_portal
    username: root
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # Use 'validate', 'update', 'create', or 'create-drop' based on your use case
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true