spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/exam_portal
    username: postgres
    password: 123456789
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # Use 'validate', 'update', 'create', or 'create-drop' based on your use case
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true



